# Nome da Aplicacao
spring.application.name=scripta-backend

# Configuracao Inteligente de Banco de Dados
# Se tiver uma URL definida no ambiente (na nuvem), usa ela. Se nao, usa o H2 local.
spring.datasource.url=${DATABASE_URL:jdbc:h2:file:./data/usuariosdb}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=${DATABASE_DRIVER:org.h2.Driver}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${DATABASE_DIALECT:org.hibernate.dialect.H2Dialect}

# Servidor
server.port=${PORT:8082}

# JWT Security
jwt.secret=uma_chave_super_secreta_e_longa_para_funcionar_o_token_123456789
jwt.expiration=86400000
jwt.expiration-ms=86400000