spring.application.name=scripta-backend

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Servidor
server.port=${PORT:8080}

# spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JWT Security
jwt.secret=uma_chave_super_secreta_e_longa_para_funcionar_o_token_123456789
jwt.expiration=86400000
jwt.expiration-ms=86400000